CREATE TABLE analyzer
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model         VARCHAR(255),
    serial_number VARCHAR(255),
    CONSTRAINT pk_analyzer PRIMARY KEY (id)
);

ALTER TABLE analyzer
    ADD CONSTRAINT uc_analyzer_serialnumber UNIQUE (serial_number);