CREATE TABLE company
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title     VARCHAR(255)                            NOT NULL,
    telephone VARCHAR(255),
    email     VARCHAR(255),
    address   VARCHAR(255),
    CONSTRAINT pk_company PRIMARY KEY (id)
);

ALTER TABLE company
    ADD CONSTRAINT uc_company_title UNIQUE (title);